# Generated by Django 5.1.7 on 2025-03-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('featured_product', 'Featured Product')], default='new_arrival', max_length=20),
        ),
    ]
