# Generated by Django 5.1.7 on 2025-03-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0003_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('featured_product', 'Featured Product')], max_length=20),
        ),
    ]
