# Generated by Django 5.1.7 on 2025-04-06 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0005_earphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='earphone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Base_app.earphone'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_type',
            field=models.CharField(choices=[('new_arrival', 'New Arrival'), ('featured_product', 'Featured Product'), ('earphone', 'Earphone')], max_length=20),
        ),
    ]
