# Generated by Django 5.1.7 on 2025-04-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0010_cartitem_techgadget_alter_cartitem_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='earphone',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='earphone',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LIM', 'Limited Stock')], default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='featured_product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='featured_product',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LIM', 'Limited Stock')], default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='headphone',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='headphone',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LIM', 'Limited Stock')], default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='new_arrival',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='new_arrival',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LIM', 'Limited Stock')], default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='techgadget',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description', null=True),
        ),
        migrations.AddField(
            model_name='techgadget',
            name='stock_status',
            field=models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock'), ('LIM', 'Limited Stock')], default='IN', max_length=3),
        ),
    ]
