# Generated by Django 5.1.7 on 2025-04-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0014_allproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproduct',
            name='category',
            field=models.CharField(choices=[('featured', 'Featured'), ('new_arrival', 'New Arrival'), ('earphone', 'Earphone'), ('headphone', 'Headphone'), ('tech_gadget', 'TechGadget')], max_length=20),
        ),
    ]
